name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ABI: "armeabi-v7a,arm64-v8a,x86,x86_64"
      NDK_VERSION: "28.0.13004108"
      CMAKE_VERSION: "3.31.6"
      ANDROID_PLATFORM: "21"
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;${{ env.NDK_VERSION }} cmake;${{ env.CMAKE_VERSION }}"

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "3.0.6"
          actions-cache-folder: ".xmake-cache"

      - name: Package
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
        run: |
          IFS=',' read -ra ARCHS <<< "$ABI"
          for arch in "${ARCHS[@]}"; do
            xmake config --yes --verbose --mode=releasedbg --plat=android --arch="$arch"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android.tar.xz
          path: build/*
          compression-level: 0
          if-no-files-found: error