name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: "28.0.13004108"
      CMAKE_VERSION: "3.31.6"
      ANDROID_PLATFORM: "21"
    strategy:
      fail-fast: false
      matrix:
        arch: ["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -y opencc

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;${{ env.NDK_VERSION }} cmake;${{ env.CMAKE_VERSION }}"

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "3.0.6"
          actions-cache-folder: ".xmake-cache"

      - name: Package
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
        run: |
          xmake config --yes --verbose --mode=releasedbg --plat=android --arch=${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifact-android-${{ matrix.arch }}
          path: out/android/*.tar.xz